// data/pharmadata.ts

export interface Product {
  id: string;
  name: string;
  genericName?: string;
  price: number;
  mrp: number;
  discount?: number;
  description: string;
  image: string;
  category: string;
  subcategory?: string;
  manufacturer: string;
  packSize: string;
  prescription: boolean;
  popular?: boolean;
  inStock: boolean;
  rating?: number;
  reviews?: number;
  tags?: string[];
  dosage?: string;
  sideEffects?: string[];
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  subcategories?: string[];
}

export const categories: Category[] = [
  { id: "all", name: "All Medicines", icon: "💊" },
  { id: "fever", name: "Fever & Pain", icon: "🌡️", subcategories: ["Paracetamol", "Ibuprofen", "Aspirin"] },
  { id: "diabetes", name: "Diabetes Care", icon: "🩸", subcategories: ["Tablets", "Insulin", "Glucometers"] },
  { id: "vitamins", name: "Vitamins & Supplements", icon: "💪", subcategories: ["Multivitamins", "Vitamin D", "Vitamin B12", "Calcium"] },
  { id: "antibiotics", name: "Antibiotics", icon: "🔬", subcategories: ["Penicillins", "Macrolides", "Cephalosporins"] },
  { id: "allergy", name: "Allergy & Asthma", icon: "😤", subcategories: ["Antihistamines", "Inhalers", "Nasal Sprays"] },
  { id: "digestive", name: "Digestive Health", icon: "🧬", subcategories: ["Antacids", "PPIs", "Probiotics"] },
  { id: "cardiac", name: "Cardiac Care", icon: "❤️", subcategories: ["Blood Pressure", "Cholesterol", "Blood Thinners"] },
  { id: "skincare", name: "Skin Care", icon: "✨", subcategories: ["Antifungal", "Antibacterial", "Moisturizers"] },
  { id: "womens", name: "Women's Health", icon: "🌸", subcategories: ["Pregnancy", "Hormonal", "Supplements"] },
  { id: "childcare", name: "Child Care", icon: "👶", subcategories: ["Drops", "Syrups", "Vitamins"] },
  { id: "ayurvedic", name: "Ayurvedic", icon: "🌿", subcategories: ["Chyawanprash", "Herbal Juices", "Oils"] },
  { id: "devices", name: "Medical Devices", icon: "📟", subcategories: ["Thermometers", "BP Monitors", "Glucometers"] },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Paracetamol 500mg",
    genericName: "Acetaminophen",
    price: 18,
    mrp: 25,
    discount: 28,
    description: "Effective fever reducer and pain reliever for headaches, body aches, and mild pain.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop",
    category: "fever",
    subcategory: "Paracetamol",
    manufacturer: "Cipla Ltd.",
    packSize: "15 Tablets",
    prescription: false,
    popular: true,
    inStock: true,
    rating: 4.5,
    reviews: 234,
    tags: ["fever", "pain", "headache"],
    dosage: "1-2 tablets every 4-6 hours",
    sideEffects: ["Nausea", "Allergic reactions (rare)"],
  },
  {
    id: "2",
    name: "Vitamin D3 60K",
    genericName: "Cholecalciferol",
    price: 95,
    mrp: 120,
    discount: 21,
    description: "Weekly vitamin D supplement for bone health and immunity boost.",
    image: "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=200&h=200&fit=crop",
    category: "vitamins",
    subcategory: "Vitamin D",
    manufacturer: "Abbott Healthcare",
    packSize: "4 Capsules",
    prescription: false,
    popular: true,
    inStock: true,
    rating: 4.8,
    reviews: 567,
    tags: ["vitamins", "bone health", "immunity"],
    dosage: "1 capsule weekly",
    sideEffects: ["Usually well tolerated"],
  },
  {
    id: "3",
    name: "Metformin 500mg",
    genericName: "Metformin Hydrochloride",
    price: 65,
    mrp: 85,
    discount: 24,
    description: "First-line medication for type 2 diabetes management.",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=200&h=200&fit=crop",
    category: "diabetes",
    subcategory: "Tablets",
    manufacturer: "Sun Pharma",
    packSize: "10 Tablets",
    prescription: true,
    inStock: true,
    rating: 4.6,
    reviews: 189,
    tags: ["diabetes", "blood sugar"],
    dosage: "As prescribed by doctor",
    sideEffects: ["Nausea", "Diarrhea", "Metallic taste"],
  },
  {
    id: "4",
    name: "Azithromycin 500mg",
    genericName: "Azithromycin",
    price: 120,
    mrp: 150,
    discount: 20,
    description: "Broad-spectrum antibiotic for bacterial infections.",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=200&h=200&fit=crop",
    category: "antibiotics",
    subcategory: "Macrolides",
    manufacturer: "Pfizer",
    packSize: "3 Tablets",
    prescription: true,
    inStock: true,
    rating: 4.4,
    reviews: 312,
    tags: ["antibiotic", "infection"],
    dosage: "As prescribed by doctor",
    sideEffects: ["Stomach upset", "Diarrhea"],
  },
  {
    id: "5",
    name: "Cetirizine 10mg",
    genericName: "Cetirizine Hydrochloride",
    price: 28,
    mrp: 35,
    discount: 20,
    description: "Non-drowsy allergy relief for sneezing, runny nose, and itching.",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&h=200&fit=crop",
    category: "allergy",
    subcategory: "Antihistamines",
    manufacturer: "Dr. Reddy's",
    packSize: "10 Tablets",
    prescription: false,
    inStock: true,
    rating: 4.7,
    reviews: 445,
    tags: ["allergy", "antihistamine"],
    dosage: "1 tablet daily",
    sideEffects: ["Mild drowsiness", "Dry mouth"],
  },
  {
    id: "6",
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    price: 52,
    mrp: 65,
    discount: 20,
    description: "Proton pump inhibitor for acid reflux and heartburn relief.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop",
    category: "digestive",
    subcategory: "PPIs",
    manufacturer: "Dr. Reddy's",
    packSize: "15 Capsules",
    prescription: false,
    inStock: true,
    rating: 4.5,
    reviews: 278,
    tags: ["acidity", "heartburn", "gerd"],
    dosage: "1 capsule before breakfast",
    sideEffects: ["Headache", "Stomach pain"],
  },
  {
    id: "7",
    name: "B-Complex Forte",
    genericName: "Vitamin B Complex",
    price: 145,
    mrp: 180,
    discount: 19,
    description: "Complete vitamin B supplement with B1, B2, B6, B12 for energy and metabolism.",
    image: "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=200&h=200&fit=crop",
    category: "vitamins",
    subcategory: "Multivitamins",
    manufacturer: "Abbott",
    packSize: "30 Tablets",
    prescription: false,
    popular: true,
    inStock: true,
    rating: 4.6,
    reviews: 523,
    tags: ["energy", "metabolism", "nerve health"],
    dosage: "1 tablet daily",
    sideEffects: ["Urine discoloration (harmless)"],
  },
  {
    id: "8",
    name: "Calcium 500mg + D3",
    genericName: "Calcium Carbonate + Vitamin D3",
    price: 175,
    mrp: 220,
    discount: 20,
    description: "Calcium supplement with Vitamin D3 for bone health and osteoporosis prevention.",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=200&h=200&fit=crop",
    category: "vitamins",
    subcategory: "Calcium",
    manufacturer: "Cipla",
    packSize: "30 Tablets",
    prescription: false,
    inStock: true,
    rating: 4.7,
    reviews: 356,
    tags: ["bone health", "calcium", "osteoporosis"],
    dosage: "1 tablet twice daily",
    sideEffects: ["Constipation", "Bloating"],
  },
  {
    id: "9",
    name: "Amlodipine 5mg",
    genericName: "Amlodipine Besylate",
    price: 42,
    mrp: 55,
    discount: 24,
    description: "Calcium channel blocker for high blood pressure management.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop",
    category: "cardiac",
    subcategory: "Blood Pressure",
    manufacturer: "Sun Pharma",
    packSize: "10 Tablets",
    prescription: true,
    inStock: true,
    rating: 4.5,
    reviews: 167,
    tags: ["blood pressure", "hypertension"],
    dosage: "As prescribed by doctor",
    sideEffects: ["Swelling", "Dizziness"],
  },
  {
    id: "10",
    name: "Atorvastatin 10mg",
    genericName: "Atorvastatin",
    price: 85,
    mrp: 110,
    discount: 23,
    description: "Statin medication for lowering cholesterol and reducing heart disease risk.",
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=200&h=200&fit=crop",
    category: "cardiac",
    subcategory: "Cholesterol",
    manufacturer: "Pfizer",
    packSize: "10 Tablets",
    prescription: true,
    inStock: true,
    rating: 4.6,
    reviews: 234,
    tags: ["cholesterol", "lipid", "heart"],
    dosage: "As prescribed by doctor",
    sideEffects: ["Muscle pain", "Liver enzyme changes"],
  },
  {
    id: "11",
    name: "Clotrimazole Cream",
    genericName: "Clotrimazole 1%",
    price: 65,
    mrp: 85,
    discount: 24,
    description: "Antifungal cream for skin infections like ringworm and athlete's foot.",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&h=200&fit=crop",
    category: "skincare",
    subcategory: "Antifungal",
    manufacturer: "Bayer",
    packSize: "15g Tube",
    prescription: false,
    inStock: true,
    rating: 4.4,
    reviews: 189,
    tags: ["antifungal", "skin infection"],
    dosage: "Apply twice daily",
    sideEffects: ["Mild irritation"],
  },
  {
    id: "12",
    name: "Folic Acid 5mg",
    genericName: "Folic Acid",
    price: 32,
    mrp: 40,
    discount: 20,
    description: "Essential for pregnancy and red blood cell formation.",
    image: "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=200&h=200&fit=crop",
    category: "womens",
    subcategory: "Pregnancy",
    manufacturer: "Cipla",
    packSize: "30 Tablets",
    prescription: false,
    inStock: true,
    rating: 4.8,
    reviews: 412,
    tags: ["pregnancy", "folic acid", "anemia"],
    dosage: "1 tablet daily",
    sideEffects: ["Usually well tolerated"],
  },
  {
    id: "13",
    name: "Dolo 650",
    genericName: "Paracetamol 650mg",
    price: 28,
    mrp: 35,
    discount: 20,
    description: "Extra strength paracetamol for fever and moderate pain relief.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop",
    category: "fever",
    subcategory: "Paracetamol",
    manufacturer: "Micro Labs",
    packSize: "15 Tablets",
    prescription: false,
    popular: true,
    inStock: true,
    rating: 4.9,
    reviews: 789,
    tags: ["fever", "pain", "headache"],
    dosage: "1-2 tablets every 6-8 hours",
    sideEffects: ["Rare allergic reactions"],
  },
  {
    id: "14",
    name: "Digene Tablets",
    genericName: "Aluminium Hydroxide + Magnesium",
    price: 38,
    mrp: 48,
    discount: 21,
    description: "Fast-acting antacid for acidity, gas, and indigestion relief.",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop",
    category: "digestive",
    subcategory: "Antacids",
    manufacturer: "Abbott",
    packSize: "15 Tablets",
    prescription: false,
    inStock: true,
    rating: 4.7,
    reviews: 567,
    tags: ["acidity", "gas", "indigestion"],
    dosage: "1-2 tablets as needed",
    sideEffects: ["Constipation or diarrhea"],
  },
  {
    id: "15",
    name: "Zincovit Tablets",
    genericName: "Multivitamin + Zinc",
    price: 85,
    mrp: 105,
    discount: 19,
    description: "Multivitamin with zinc for immunity and overall health.",
    image: "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=200&h=200&fit=crop",
    category: "vitamins",
    subcategory: "Multivitamins",
    manufacturer: "Apex Labs",
    packSize: "15 Tablets",
    prescription: false,
    popular: true,
    inStock: true,
    rating: 4.5,
    reviews: 345,
    tags: ["immunity", "multivitamin", "zinc"],
    dosage: "1 tablet daily",
    sideEffects: ["Usually well tolerated"],
  },
  {
    id: "16",
    name: "Montair LC",
    genericName: "Montelukast + Levocetirizine",
    price: 125,
    mrp: 160,
    discount: 22,
    description: "Combination for allergic rhinitis and asthma management.",
    image: "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=200&h=200&fit=crop",
    category: "allergy",
    subcategory: "Antihistamines",
    manufacturer: "Cipla",
    packSize: "10 Tablets",
    prescription: true,
    inStock: true,
    rating: 4.6,
    reviews: 234,
    tags: ["allergy", "asthma", "antihistamine"],
    dosage: "1 tablet at bedtime",
    sideEffects: ["Drowsiness", "Headache"],
  },
];

export const sortOptions = [
  { value: "popular", label: "Popularity" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "discount", label: "Discount" },
  { value: "rating", label: "Customer Rating" },
];

export const availabilityOptions = [
  { value: "all", label: "All Products" },
  { value: "in-stock", label: "In Stock" },
  { value: "prescription", label: "Prescription Required" },
  { value: "otc", label: "OTC" },
];

export const priceRanges = [
  { min: 0, max: 50, label: "Under ₹50" },
  { min: 50, max: 100, label: "₹50 - ₹100" },
  { min: 100, max: 200, label: "₹100 - ₹200" },
  { min: 200, max: 500, label: "₹200 - ₹500" },
  { min: 500, max: null, label: "Above ₹500" },
];